services:
  minidlna:
    build: . # image: minidlna:latest
    container_name: minidlna
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./cache:/var/cache/minidlna
      - ~/Загрузки:/media
    environment:
      - MINIDLNA_MEDIA_DIR=/media
      - MINIDLNA_FRIENDLY_NAME=My DLNA Server
