services:
  minidlna:
    image: minidlna:latest
    build:
      context: .
      args:
        ALPINE_TAG: "3.21.3"
        MINIDLNA_VER: "1.3.3-r1"
    pull_policy: never
    container_name: minidlna
    network_mode: host
    restart: unless-stopped
    volumes:
      - ~/Загрузки:/media
    # environment:
      # - MINIDLNA_MEDIA_DIR=/media
      # - MINIDLNA_FRIENDLY_NAME=Медиа
