x-minidlna-common: &minidlna-common
  image: ${MINIDLNA_IMAGE:-minidlna}:${MINIDLNA_TAG:-latest}
  build:
    context: .
    args:
      ALPINE_TAG: "${ALPINE_TAG:-3.21.3}"
      MINIDLNA_VER: "${MINIDLNA_VER:-1.3.3-r1}"
  pull_policy: never
  network_mode: host
  restart: always
  healthcheck:
    test: ["CMD", "curl", "-f", "127.0.0.1:8200"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 10s
services:
  minidlna:
    <<: *minidlna-common
    container_name: minidlna
    volumes:
      - ~/Загрузки:/media
