services:
  minidlna:
    build: . # image: minidlna:latest
    container_name: minidlna
    network_mode: host
    restart: unless-stopped
    volumes:
      - ~/Загрузки:/minidlna
    # environment:
      # - MINIDLNA_MEDIA_DIR=/minidlna
      # - MINIDLNA_FRIENDLY_NAME=My DLNA Server
