name: Docker Lint

on: 
  push:
    branches:
      - main
  pull_request:
      - main

jobs:
  docker-lint:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          ignore: DL3018,DL3020

      - name: Lint docker-compose.yml
        run: docker compose -f docker-compose.yml config
